HMWK3/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace HMWK3.Models
{
    public class FileModel
    {

        [Display(Name = "File Name")]
        public string FileName { get; set; }

        [Required(ErrorMessage = "Please select file.")]
        [Display(Name = "Browse File")]
        public HttpPostedFileBase[] Files { get; set; }
    
    }
}

HMWK3/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HMWK3.Models;

namespace HMWK3.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        public ActionResult Index()
        {
            
           string[] filePaths = Directory.GetFiles(Server.MapPath("~/Content/Media/Files/"));

            List<FileModel> MyFiles = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                MyFiles.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(MyFiles);
        }


        public FileResult DownloadFile(string fileName)
        {
           
            string path = Server.MapPath("~/Content/Media/Files/") + fileName;

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            string path = Server.MapPath("~/Content/Media/Files/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

HMWK3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMWK3.Controllers
{
    public class HomeController : Controller
    {

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase mediafiles)   //HttpRequestBase: We can use HttpRequestBase class property named Request to get collection of files or single file.
        //HttpPostedFileBase: This is the easiest way to read the uploaded files into the controller 
        {
            if (mediafiles != null)
            {
                // extract only the filename

                var fileName = Path.GetFileName(mediafiles.FileName);
                var RadioButton = Request["radiobutton"];
                if (RadioButton == "Document")
                {
                    // var ServerSavePath = Path.Combine(Server.MapPath("~/App_Data/Media/Files/") + fileName);
                    var filepath = Path.Combine(Server.MapPath("~/Content/Media/Files/"), fileName);
                    //Save file to server folder
                    // file.SaveAs(ServerSavePath);
                    mediafiles.SaveAs(filepath);
                    //assigning file uploaded status to ViewBag for showing message to user.
                    ViewBag.UploadStatus = " files uploaded successfully.";
                }
                else if (RadioButton == "Image")
                {
                    // var ServerSavePath = Path.Combine(Server.MapPath("~/App_Data/Media/Files/") + fileName);
                    var filepath = Path.Combine(Server.MapPath("~/Content/Media/Images/"), fileName);
                    //Save file to server folder
                    // file.SaveAs(ServerSavePath);
                    mediafiles.SaveAs(filepath);
                    //assigning file uploaded status to ViewBag for showing message to user.
                    ViewBag.UploadStatus = " files uploaded successfully.";
                }
                else if (RadioButton == "Video")
                {
                    // var ServerSavePath = Path.Combine(Server.MapPath("~/App_Data/Media/Files/") + fileName);
                    var filepath = Path.Combine(Server.MapPath("~/Content/Media/Videos/"), fileName);
                    //Save file to server folder
                    // file.SaveAs(ServerSavePath);
                    mediafiles.SaveAs(filepath);
                    //assigning file uploaded status to ViewBag for showing message to user.
                    ViewBag.UploadStatus = " files uploaded successfully.";
                }

            }
            return RedirectToAction("Index");
        }

                public ActionResult About()
                {
                    return View();
                }
    }
}
    

HMWK3/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HMWK3.Models;

namespace HMWK3.Controllers
{
    public class ImageController : Controller
    {
        // GET: Images
        public ActionResult Index()
        {

            string[] filePaths = Directory.GetFiles(Server.MapPath("~/Content/Media/Images/"));

            List<FileModel> MyFiles = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                MyFiles.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(MyFiles);
        }


        public FileResult DownloadFile(string fileName)
        {

            string path = Server.MapPath("~/Content/Media/Images/") + fileName;

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            string path = Server.MapPath("~/Content/Media/Images/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }

   
}

HMWK3/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HMWK3.Models;

namespace HMWK3.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {

            string[] filePaths = Directory.GetFiles(Server.MapPath("~/Content/Media/Videos/"));

            List<FileModel> MyFiles = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                MyFiles.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(MyFiles);
        }


        public FileResult DownloadFile(string fileName)
        {

            string path = Server.MapPath("~/Content/Media/Videos/") + fileName;

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            string path = Server.MapPath("~/Content/Media/Videos/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

HMWK3/Views/File/Index.cshtml
@using HMWK3.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}

<h1>Documents</h1>
<h3>List of files</h3>

<head>
    <style type="text/css">

        .container {
            
            overflow:auto;
           
        }

        thead {

            position:sticky;
            top:0;
            background-color:burlywood
        }

        .t {
            text-align: center;
            vertical-align: middle;
        }
    </style>
</head>


<div class="container">
    <div class="well-sm">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="col-lg-8">File Name</th>
                    <th class="t, col-lg-2">Download Option</th>
                    <th class="t, col-lg-2">Delete Option</th>
                </tr>
            </thead>
            
            @foreach (FileModel file in Model)
            {
                <tr>
                    <td>@file.FileName</td>
                    <td>
                        <button class="btn-info">
                            @Html.ActionLink("Download", "DownloadFile",
                             new { fileName = file.FileName })
                        </button>
                    </td>
                    <td>
                        <button class="btn-danger">
                            @Html.ActionLink("DELETE", "DeleteFile",
                           new { fileName = file.FileName },
                           new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

HMWK3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1>A Little More About Me?</h1><br />
<h2>-Let's see...</h2>

<head>
    <style type="text/css">

      img{
          position:center;
          width:240px;
          height:350px;
      }

    </style>
</head>


<div class="container">
<div class="row">
    <div class="col-sm-10 col-md-6 col-lg-6 ">
        <h3>
            <b>A Biography On Bianca!</b>
        </h3>
        <br />
        <p>
            My name, in case the bold heading above was a little vague, is Bianca Kubayi. I am an 18 year old gift to the world,
            who is studying her second year of BCom informatics Information Systems in the University Of Pretoria.
            Therefore it goes without saying that I have mere dust particles of mental stability in me but I can not completely blame University for that,
            I didn't have much sanity before in all honesty.
            I'd say what I love the most about my degree is how broad it is, how I get to dip a toe into analytics, systems, design, programming so I have quite a heavily coated toe now.
            And it gets more and more interesting, the more I learn and the more I dip said toe of mine. I feel content and a slight tingle of happiness towards my degree so I pray all the time that my best is enough.
            <br />
            <br />
            I am from Pretoria originally, went to primary school and high school in the city of Pretoria. I have lived in Pretoria my whole life basically,
            so I understand why it may seem odd to others that I get lost on my way home sometimes. What can I say, I can't be beautiful, smart, funny and be good at directions.
            You simply can't have it all in this world.
            My favourite number is two (I think it's a thing to have a favourite number, isn't it?). My favourite colour is green,
            keep in mind that I use favouritism and obsessiveness synonymously so my entire wordrobe being green should be normal.
            <br />
            <br />
            I have 2 siblings, one older sister and one younger sister. I know what you're thinking, yes they do wish they were me but I remind them all the time they aren't all that bad
            and they can live happily knowing they are related to me. I have a hardworking mother who is a nurse, so going to the doctor is a myth to me. I'm still building up the courage to explain to her that Vicks can't be the cure to everything.
            I do hope to some day bloom into a little something that is big enough to make her proud.
            <br />
            <br />
            I could go on for centuries about myself but the small tale I've told will suffice for now.
        </p>
    </div>
    
   <div class="col-sm-10 col-md-6 col-lg-6">
       <h3><b>Bianca Kubayi</b></h3>
       <div >

           <img src="~/Content/pictures/picture.jpg" />

       </div>
   </div>
</div>
</div>

HMWK3/Views/Home/Index.cshtml
@model HMWK3.Models.FileModel
@{
    ViewBag.Title = "Home Page";
}

<div class="well-lg">
    <h1>DIA MEDIA</h1>
    <h3>Media uploading made easy</h3>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-10 col-md-6 col-lg-6 ">
            <h2>DESCRIPTION ON DIA MEDIA</h2>
            <p>
                This is a short description on this system:
                <br />
                DIA MEDIA - `Media uploading made easy` - allows you to upload media files.
                You can upload videos, images or files. You are able to select a file or media of your choice from your computer and upload it through the form under Option Selection,
                which is the file uploading section that will submit your file or media and upload it.
                The uploaded files can be displayed and viewed. You can download and delete uploaded media.
                All of this is done through MVC and the code can be viewed through Visual Studios.
            </p>
        </div>
        <div class="col-sm-8 col-md-4 col-lg-4">
            <h2>OPTION SELECTION</h2>

            <div class="form-horizontal">
                @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))

                {
                    <input type="radio" id="doc" name="radiobutton" value="Document" />
                    <label for="doc">Document</label> <br />
                    <input type="radio" id="img" name="radiobutton" value="Image" />
                    <label for="img">Image</label> <br />
                    <input type="radio" id="vid" name="radiobutton" value="Video" />
                    <label for="vid">Video</label>

                    <div><input type="file" id="mediafiles" name="mediafiles" value="Choose file.." /></div>
                    <br />

                    <div><input type="submit" value="Upload" /></div>
                    <br />
                    <div>@ViewBag.UploadStatus</div>
                }
            </div>
        </div>

    </div>
</div>
<!-- Script for checked radio button
<script type="text/javascript">

        $(document).ready(function () {

                $("#doc").prop("checked", true);

        });
</script>
    -->

HMWK3/Views/Image/Index.cshtml
@using HMWK3.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}

<h1>Images</h1>
<h3>A Bunch of pictures</h3>

<head>
    <style type="text/css">

        .container {
            overflow: auto;
            
        }

       .thumbnail{
           border-color:darkgrey;

       }

       .col-xs-2{
           display:flex;
           justify-content:center;
           margin:3px;
       }

    </style>
</head>

<div class="container">
    <div class="row">
        @foreach (FileModel image in Model)
         {

                <div class="col-md-4">
                     <div class="thumbnail">
                         <a>
                             <img src="~/Content/Media/Images/"@Path.GetFileName(image.FileName) alt="Image">
                         </a>
                           
                             <div class="caption">
                                <p>@image.FileName</p>
                            </div>
                             <div class="row">
                                 <div class="col-xs-2">
                                     <button class="btn-info">
                                         @Html.ActionLink("Download", "DownloadFile",
                                          new { fileName = image.FileName })
                                     </button>
                                 </div>
                                 
                                 <div class="col-xs-2">
                                     <button class="btn-danger">
                                         @Html.ActionLink("DELETE", "DeleteFile",
                                        new { fileName = image.FileName },
                                        new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                                     </button>
                                 </div>
                             </div>
                        
                    </div>
              </div>
               
         }
        
    </div>
</div>

<script>
$(document).ready(function ($) {
$(".gallery a").fancybox();
});
</script>

HMWK3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle glyphicon-m" data-toggle="dropdown" href="#">
                          Dia Media Menu<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Files", "Index", "File")</li>
                            <li>@Html.ActionLink("Images", "Index", "Image")</li>
                            <li>@Html.ActionLink("Videos", "Index", "Video")</li>
                            <li>@Html.ActionLink("About Me", "About", "Home")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Files", "Index", "File")</li>
                    <li>@Html.ActionLink("Images", "Index", "Image")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Video")</li>
                    <li>@Html.ActionLink("About Me", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Homework assignment 3</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HMWK3/Views/Video/Index.cshtml
@using HMWK3.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}

<h1>Videos</h1>
<h3>A Bunch Of Videos</h3>


<div class="container">
    <div class="row">
        @foreach (FileModel video in Model)
        {

            <div class="col-md-4">
                <div class="thumbnail">
                    <video>
                        <a>
                            <source src="~/Content/Media/Videos/@Path.GetFileName(video.FileName)" alt="Video">
                        </a>
                    </video>
                    <div class="caption">
                        <p>@video.FileName</p>
                    </div>
                    <div class="row">
                        <div class="col-xs-2" style="padding:inherit;">
                            <button class="btn-info">
                                @Html.ActionLink("Download", "DownloadFile",
                                 new { fileName = video.FileName })
                            </button>
                        </div>
                        <div class="col-xs-2" style="padding:inherit;">
                            <button class="btn-danger">
                                @Html.ActionLink("DELETE", "DeleteFile",
                               new { fileName = video.FileName },
                               new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                            </button>
                        </div>
                    </div>

                </div>
            </div>

        }

    </div>
</div>

<script>
$(document).ready(function ($) {
$("a").fancybox();
});
</script>